### ISSUE TITLE
just upgraded to home assistant 0.105.3 now getting ModuleNotFoundError

### ISSUE THREAD

**Issue by bobsiopener** [mlowijs/hass_tesla_v2#4]
**Describe the bug**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tesla_cc/__init__.py", line 42, in setup
    from tesla_api import TeslaApiClient, AuthenticationError, ApiError
ModuleNotFoundError: No module named 'tesla_api'

**Comment by chezpaul** [comment]
Got he same error

2020-02-12 10:27:36 ERROR (MainThread) [homeassistant.setup] Error during setup of component tesla_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tesla_cc/__init__.py", line 42, in setup
    from tesla_api import TeslaApiClient, AuthenticationError, ApiError
ModuleNotFoundError: No module named 'tesla_api'

**Comment by dvb76** [comment]
I've got the same issue. Tesla_cc failed to load. Any news on this? As indeed the standard component does not work properly on the wake up of the car.

**Comment by BDIs01** [comment]
I am getting the same error:
I've updated the manefest.json mentioned by KennedyShead and it still isn't working.  It looks like Tesla updated their API.  I had to update a few of my other Tesla apps as well.


Logger: homeassistant.setup
Source: custom_components/tesla_cc/__init__.py:42
First occurred: 8:12:12 AM (1 occurrences)
Last logged: 8:12:12 AM
Error during setup of component tesla_cc

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tesla_cc/__init__.py", line 42, in setup
    from tesla_api import TeslaApiClient, AuthenticationError, ApiError
ModuleNotFoundError: No module named 'tesla_api'

**Comment by RobHofmann** [comment]
This is due to the new changes which provide support for MFA on your Tesla account.

**Comment by aceonce** [comment]
Same issue for me, any ETA on fixes? Thanks

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/tesla_cc/__init__.py", line 42, in setup
from tesla_api import TeslaApiClient, AuthenticationError, ApiError
ModuleNotFoundError: No module named 'tesla_api'
