### ISSUE TITLE
Integration fails

### ISSUE THREAD

**Issue by drlauridsen** [mlowijs/hass_tesla_v2#6]
HA 0.116.1
Installed component with HACS.
Created tesla.yaml
Created include in config.yaml

On restart this error is shown

![Screenshot_20201013-171236_Home Assistant](https://user-images.githubusercontent.com/61352332/95880085-6a435900-0d77-11eb-9b2b-18fbca948243.jpg)

**Comment by naseemr** [comment]
I am getting error too.
2021-02-02 15:53:53 ERROR (MainThread) [homeassistant.setup] Error during setup of component tesla_cc
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/tesla_cc/__init__.py", line 54, in setup
    vehicles = api_client.list_vehicles()
  File "/srv/homeassistant/lib/python3.9/site-packages/tesla_api/__init__.py", line 90, in list_vehicles
    return [Vehicle(self, vehicle) for vehicle in self.get('vehicles')]
  File "/srv/homeassistant/lib/python3.9/site-packages/tesla_api/__init__.py", line 68, in get
    self.authenticate()
  File "/srv/homeassistant/lib/python3.9/site-packages/tesla_api/__init__.py", line 54, in authenticate
    self._token = self._get_new_token()
  File "/srv/homeassistant/lib/python3.9/site-packages/tesla_api/__init__.py", line 32, in _get_new_token
    raise AuthenticationError(response_json['response'])
tesla_api.AuthenticationError: Authentication to the Tesla API failed: endpoint_deprecated:_please_update_your_app.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/tesla_cc/__init__.py", line 64, in setup
    _LOGGER.error(ex.message)
AttributeError: 'AuthenticationError' object has no attribute 'message'

**Comment by BDIs01** [comment]
Anyone have a fix for this.  It looks like Tesla updated their API and now none of the Tesla integrations for Home Assistant are working.

**Comment by naseemr** [comment]
Still not working for me

**Comment by meklenborg** [comment]
@drlauridsen did you solve this issue?
I am also experiencing this and I am looking for clues.

**Comment by naseemr** [comment]
Yes, with 2022.2.4 and this custom integration https://github.com/alandtse/tesla
